services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy<D-s>
    volumes:
      - redisinsight_data:/db

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
